# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-10 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20181008_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_status_id',
            field=models.IntegerField(choices=[(1, '上架'), (2, '在线'), (3, '离线'), (4, '下架')], default=1),
        ),
    ]
