# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-11 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_server_server_status_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='latest_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
