# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-15 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20180814_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=32),
        ),
    ]
