"""
Django settings for auto project.

Generated by 'django-admin startproject' using Django 1.11.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'tpcmbcq70c*3ht(j9(!1t)%2(&mt@i@lfa4g5vhbz8lh@t0830'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web.apps.WebConfig',
    'rbac.apps.RbacConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'auto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'auto.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

#######################菜单列表
# MENU = ["用户列表", "业务列表", "主机列表"]
# INFO=[{"user":"用户列表"},{"host":"主机列表"},{"home":"业务列表"}]
MENU_LIST = [
    {
        'title': '用户管理',
        'icon': 'fa-clipboard',
        'class': 'hide',  # 默认菜单都是隐藏的
        'children': [
            {'title': '个人中心', 'url': '/web/info/', 'is_menu': True},
            {'title': '用户列表', 'url': '/web/user/', 'is_menu': True},
            {'title': '添加用户', 'url': '/web/add_user/', 'is_menu': False, 'parent_index': 1},
            {'title': '编辑用户', 'url': '/web/edit_user/(\d+)/', 'is_menu': False, 'parent_index': 1},
            # false就是不在页面上直接显示这个菜单 ,parent_index=1就是代表children这个列表里面索引等于1的选项
        ]
    },
    {
        'title': '商品管理',
        'icon': 'fa-clipboard',
        'class': 'hide',
        'children': [
            {'title': '活动中心', 'url': '/web/orderinfo/', 'is_menu': True,},
            {'title': '订单管理', 'url': '/web/orderlist/', 'is_menu': True},
            {'title': '添加订单', 'url': '/web/add_order/', 'is_menu': False, 'parent_index': 1},
            {'title': '编辑订单', 'url': '/web/edit_order/(\d+)/', 'is_menu': False, 'parent_index': 1},
        ]
    }
]
