# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-13 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField()),
                ('birthday2', models.DateTimeField(null=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('last_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
