# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181201_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='uid',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='上线文件包名称'),
        ),
    ]
