# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-22 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20181216_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='status',
            field=models.IntegerField(choices=[(1, '未获取'), (2, '待发布'), (3, '已发布'), (4, '已回滚')], default=1, verbose_name='状态'),
        ),
    ]
