# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20181223_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='Deploy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Deploy', verbose_name='发布任务'),
        ),
        migrations.AlterField(
            model_name='script',
            name='interpreter',
            field=models.CharField(choices=[('sh', 'bash'), ('py', 'python3')], default='py', max_length=16, verbose_name='解释器'),
        ),
    ]
