# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20181228_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='Deploy',
        ),
    ]
