# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-29 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_host_deploy'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployrecord',
            name='host_version',
            field=models.CharField(max_length=32, null=True, verbose_name='版本'),
        ),
    ]
