# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-05 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180805_1605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
